# Generated by Django 5.2.3 on 2025-08-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('general_hindi', 'General Hindi'), ('law_constitution', 'Law & Constitution'), ('general_knowledge', 'General Knowledge'), ('numerical_mental', 'Numerical & Mental Ability')], default='general_knowledge', max_length=20),
        ),
        migrations.AddField(
            model_name='testresult',
            name='section_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='General Knowledge', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.testpaper'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mocktest.testpaper'),
        ),
    ]
