# Generated by Django 5.2.5 on 2025-09-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0003_otpverification_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_phone_verified',
            new_name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
