# Generated by Django 5.2.5 on 2025-09-11 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0004_rename_is_phone_verified_userprofile_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['question_number']},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='section_scores',
            new_name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testpaper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.testpaper'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('general_hindi', 'General Hindi'), ('law_constitution', 'Law & Constitution'), ('general_knowledge', 'General Knowledge'), ('numerical_mental', 'Numerical & Mental Ability')], max_length=20)),
                ('question_count', models.IntegerField(default=40)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='mocktest.testpaper')),
            ],
            options={
                'unique_together': {('paper', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('subject', 'question_number')},
        ),
        migrations.RemoveField(
            model_name='question',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
    ]
