# Generated by Django 5.2.5 on 2025-09-11 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='General Knowledge', max_length=100),
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['section', 'id']},
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='answers',
            new_name='section_scores',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='testpaper',
            name='is_active',
        ),
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.testpaper'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('general_hindi', 'General Hindi'), ('law_constitution', 'Law & Constitution'), ('general_knowledge', 'General Knowledge'), ('numerical_mental', 'Numerical & Mental Ability')], default='general_knowledge', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mocktest.testpaper'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
    ]
